# Generated by Django 4.2.5 on 2024-08-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0003_profile_photo_profile_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='real_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
