# Generated by Django 4.2.5 on 2024-08-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0004_rename_real_name_profile_name_profile_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='student',
            new_name='is_teacher',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='real_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='teacher',
        ),
    ]
