# Generated by Django 4.2.5 on 2024-08-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0005_rename_student_profile_is_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='real_name',
            new_name='name',
        ),
    ]
