# Generated by Django 4.2.5 on 2024-08-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0006_rename_real_name_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_teacher',
            new_name='teacher',
        ),
    ]
