# Generated by Django 4.2.5 on 2024-08-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0007_rename_is_teacher_profile_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
