# Generated by Django 4.2.5 on 2024-09-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0008_profile_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('on_campus', 'On Campus'), ('teaching_centre', 'Teaching Centre')], max_length=20, null=True),
        ),
    ]
