# Generated by Django 4.2.5 on 2024-09-01 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0010_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='new_material',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_materials/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='CodeLabWebsite.course')),
            ],
        ),
    ]
