# Generated by Django 4.2.5 on 2024-09-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0012_course_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusupdate',
            old_name='text',
            new_name='content',
        ),
    ]
