# Generated by Django 4.2.5 on 2024-09-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0013_rename_text_statusupdate_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
