# Generated by Django 4.2.5 on 2024-09-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0014_remove_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
