# Generated by Django 4.2.5 on 2024-09-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0015_enrollment_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='blocked',
        ),
    ]
