# Generated by Django 4.2.5 on 2024-09-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0017_enrollment_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='new_enrollment',
            field=models.BooleanField(default=False),
        ),
    ]
