# Generated by Django 4.2.5 on 2024-09-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0018_course_new_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
