# Generated by Django 4.2.5 on 2024-09-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLabWebsite', '0019_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
